repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        files: \.md$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        files: \.yml$|\.yaml$
      - id: trailing-whitespace
        description: Remove trailing whitespace
      - id: end-of-file-fixer
        description: Ensure file ends with a newline

  # Hook for minifying Jekyll assets
  - repo: local
    hooks:
      - id: minify-jekyll-assets
        name: Minify Jekyll CSS and JavaScript
        entry: ./minify_jekyll_assets.sh
        language: script
        files: "\\.(js|css)$"
