# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Runtime Env
email: marcel@feneri.ch
url: "https://feneri.ch" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: marcelfenerich
github_username:  mfenerich

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-sitemap
  - jekyll-gist

header_pages:
  - about.markdown

# Google Analytics
google_analytics: G-K9TDVXHCZQ

# Consent Manager
consentmanager: 3efd495d0105b

# Disqus
disqus:
  shortname: feneri-ch

# SEO config

# Basic SEO settings
tagline: "Insights and strategies for building scalable, reliable systems."
description: "A blog dedicated to sharing knowledge and experiences from over a decade in software engineering. Covering everything from architecture best practices to hands-on project insights, this space is for professionals looking to learn, experiment, and stay updated in the fast-evolving world of tech."
author: "Marcel Fenerich"

# Social media profiles
social:
  name: Marcel Fenerich
  links:
    - https://www.linkedin.com/in/marcel-fenerich-82a104a3/

google_site_verification: 6AKp3usog4L3k7IA7ZIX2hQxmVjv_er9dbXQzE9BYOM
